log:
  path: /home/clarkmaio/Scrivania/
  level: INFO


databse:
  username: myuser
  password: mypassword



path:
  plot: plot_path
  model: model_path
  report: report_path



mlflow: none

prefect: none
